apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gke
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.2.31.0
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: nginx
