apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  yb.server: |
    yb-gke.svc.cluster.local:53 {
        errors
        cache 30
        forward . 10.2.31.0
    }
